draws_diagrams(yes).
explains_aloud(no).
needs_practice(no).
energy_peak(morning).
focus_span('>60_min').
sound_preference(lyrics).
group_size(small_group).
study_location(fixed).
exam_priority(essay).
time_pressure_panic(yes).
